name: Notify Telegram on Commit

on:
  push:
    branches:
      - master  # Change this to the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');

            const telegramToken = '${{ secrets.TELEGRAM_BOT_TOKEN }}';
            const chatId = '${{ secrets.CHAT_ID }}';
            const repository = context.repo.full_name;
            const pusher = context.payload.pusher.name;
            const commitMessage = context.payload.head_commit.message;

            const message = `New commit on ${repository} by ${pusher}: ${commitMessage}`;

            await axios.post(`https://api.telegram.org/bot${telegramToken}/sendMessage`, {
              chat_id: chatId,
              text: message,
            });
