name: Notify Telegram on Commit

on:
  push:
    branches:
      - master  # Change this to the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          telegramToken="${{ secrets.TELEGRAM_BOT_TOKEN }}"
          chatId="${{ secrets.CHAT_ID }}"
          repository="${{ github.repository }}"
          pusher="${{ github.actor }}"
          commitMessage="${{ github.event.head_commit.message }}"

          message="New commit on ${repository} by ${pusher}: ${commitMessage}"

          curl -s -X POST "https://api.telegram.org/bot${telegramToken}/sendMessage" \
            -d "chat_id=${chatId}" \
            -d "text=${message}"
